import type { Metadata } from "next";
import Header from "@/components/header/Header";
import { Footer } from "@/components/footer/Footer";

import { Inter } from "next/font/google";
import "styles/globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  /* esta parte se cambia por el json de los idiomas */
  title: "Fundación Domus",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto+Slab&display=swap"
          rel="stylesheet"
        />
      </head>
      <html lang="es">
        <body className={inter.className}>
          <Header />

          {children}

          <Footer />
        </body>
      </html>
    </>
  );
}
